projects := \
	1_1_hello_html \
	1_2_variable \
	1_3_client \
	2_2_slice_html \
	2_3_list_habits \
	3_tick \
	4_create \
	5_week \
	6_funcmap

%:
	@for project in $(projects); do (cd $${project}; make $@); done
