projects := \
	1_1_hello_html \
	1_2_client \
	2_1_time_html \
	2_2_slice_html \
	3_list \
	4_tick \
	5_create \
	6_niceties \
	7_funcmap

%:
	@for project in $(projects); do (cd $${project}; make $@); done
