// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package mocks

//go:generate minimock -i learngo-pockets/habits/internal/habit.tickAdder -o tick_adder_mock.go -n TickAdderMock -p mocks

import (
	"context"
	mm_habit "learngo-pockets/habits/internal/habit"
	"learngo-pockets/habits/internal/tick"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// TickAdderMock implements habit.tickAdder
type TickAdderMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAdd          func(ctx context.Context, id mm_habit.ID, t tick.Tick, w tick.ISOWeek) (err error)
	inspectFuncAdd   func(ctx context.Context, id mm_habit.ID, t tick.Tick, w tick.ISOWeek)
	afterAddCounter  uint64
	beforeAddCounter uint64
	AddMock          mTickAdderMockAdd
}

// NewTickAdderMock returns a mock for habit.tickAdder
func NewTickAdderMock(t minimock.Tester) *TickAdderMock {
	m := &TickAdderMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddMock = mTickAdderMockAdd{mock: m}
	m.AddMock.callArgs = []*TickAdderMockAddParams{}

	return m
}

type mTickAdderMockAdd struct {
	mock               *TickAdderMock
	defaultExpectation *TickAdderMockAddExpectation
	expectations       []*TickAdderMockAddExpectation

	callArgs []*TickAdderMockAddParams
	mutex    sync.RWMutex
}

// TickAdderMockAddExpectation specifies expectation struct of the tickAdder.Add
type TickAdderMockAddExpectation struct {
	mock    *TickAdderMock
	params  *TickAdderMockAddParams
	results *TickAdderMockAddResults
	Counter uint64
}

// TickAdderMockAddParams contains parameters of the tickAdder.Add
type TickAdderMockAddParams struct {
	ctx context.Context
	id  mm_habit.ID
	t   tick.Tick
	w   tick.ISOWeek
}

// TickAdderMockAddResults contains results of the tickAdder.Add
type TickAdderMockAddResults struct {
	err error
}

// Expect sets up expected params for tickAdder.Add
func (mmAdd *mTickAdderMockAdd) Expect(ctx context.Context, id mm_habit.ID, t tick.Tick, w tick.ISOWeek) *mTickAdderMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("TickAdderMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &TickAdderMockAddExpectation{}
	}

	mmAdd.defaultExpectation.params = &TickAdderMockAddParams{ctx, id, t, w}
	for _, e := range mmAdd.expectations {
		if minimock.Equal(e.params, mmAdd.defaultExpectation.params) {
			mmAdd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAdd.defaultExpectation.params)
		}
	}

	return mmAdd
}

// Inspect accepts an inspector function that has same arguments as the tickAdder.Add
func (mmAdd *mTickAdderMockAdd) Inspect(f func(ctx context.Context, id mm_habit.ID, t tick.Tick, w tick.ISOWeek)) *mTickAdderMockAdd {
	if mmAdd.mock.inspectFuncAdd != nil {
		mmAdd.mock.t.Fatalf("Inspect function is already set for TickAdderMock.Add")
	}

	mmAdd.mock.inspectFuncAdd = f

	return mmAdd
}

// Return sets up results that will be returned by tickAdder.Add
func (mmAdd *mTickAdderMockAdd) Return(err error) *TickAdderMock {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("TickAdderMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &TickAdderMockAddExpectation{mock: mmAdd.mock}
	}
	mmAdd.defaultExpectation.results = &TickAdderMockAddResults{err}
	return mmAdd.mock
}

// Set uses given function f to mock the tickAdder.Add method
func (mmAdd *mTickAdderMockAdd) Set(f func(ctx context.Context, id mm_habit.ID, t tick.Tick, w tick.ISOWeek) (err error)) *TickAdderMock {
	if mmAdd.defaultExpectation != nil {
		mmAdd.mock.t.Fatalf("Default expectation is already set for the tickAdder.Add method")
	}

	if len(mmAdd.expectations) > 0 {
		mmAdd.mock.t.Fatalf("Some expectations are already set for the tickAdder.Add method")
	}

	mmAdd.mock.funcAdd = f
	return mmAdd.mock
}

// When sets expectation for the tickAdder.Add which will trigger the result defined by the following
// Then helper
func (mmAdd *mTickAdderMockAdd) When(ctx context.Context, id mm_habit.ID, t tick.Tick, w tick.ISOWeek) *TickAdderMockAddExpectation {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("TickAdderMock.Add mock is already set by Set")
	}

	expectation := &TickAdderMockAddExpectation{
		mock:   mmAdd.mock,
		params: &TickAdderMockAddParams{ctx, id, t, w},
	}
	mmAdd.expectations = append(mmAdd.expectations, expectation)
	return expectation
}

// Then sets up tickAdder.Add return parameters for the expectation previously defined by the When method
func (e *TickAdderMockAddExpectation) Then(err error) *TickAdderMock {
	e.results = &TickAdderMockAddResults{err}
	return e.mock
}

// Add implements habit.tickAdder
func (mmAdd *TickAdderMock) Add(ctx context.Context, id mm_habit.ID, t tick.Tick, w tick.ISOWeek) (err error) {
	mm_atomic.AddUint64(&mmAdd.beforeAddCounter, 1)
	defer mm_atomic.AddUint64(&mmAdd.afterAddCounter, 1)

	if mmAdd.inspectFuncAdd != nil {
		mmAdd.inspectFuncAdd(ctx, id, t, w)
	}

	mm_params := TickAdderMockAddParams{ctx, id, t, w}

	// Record call args
	mmAdd.AddMock.mutex.Lock()
	mmAdd.AddMock.callArgs = append(mmAdd.AddMock.callArgs, &mm_params)
	mmAdd.AddMock.mutex.Unlock()

	for _, e := range mmAdd.AddMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAdd.AddMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAdd.AddMock.defaultExpectation.Counter, 1)
		mm_want := mmAdd.AddMock.defaultExpectation.params
		mm_got := TickAdderMockAddParams{ctx, id, t, w}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAdd.t.Errorf("TickAdderMock.Add got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAdd.AddMock.defaultExpectation.results
		if mm_results == nil {
			mmAdd.t.Fatal("No results are set for the TickAdderMock.Add")
		}
		return (*mm_results).err
	}
	if mmAdd.funcAdd != nil {
		return mmAdd.funcAdd(ctx, id, t, w)
	}
	mmAdd.t.Fatalf("Unexpected call to TickAdderMock.Add. %v %v %v %v", ctx, id, t, w)
	return
}

// AddAfterCounter returns a count of finished TickAdderMock.Add invocations
func (mmAdd *TickAdderMock) AddAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.afterAddCounter)
}

// AddBeforeCounter returns a count of TickAdderMock.Add invocations
func (mmAdd *TickAdderMock) AddBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.beforeAddCounter)
}

// Calls returns a list of arguments used in each call to TickAdderMock.Add.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAdd *mTickAdderMockAdd) Calls() []*TickAdderMockAddParams {
	mmAdd.mutex.RLock()

	argCopy := make([]*TickAdderMockAddParams, len(mmAdd.callArgs))
	copy(argCopy, mmAdd.callArgs)

	mmAdd.mutex.RUnlock()

	return argCopy
}

// MinimockAddDone returns true if the count of the Add invocations corresponds
// the number of defined expectations
func (m *TickAdderMock) MinimockAddDone() bool {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterAddCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && mm_atomic.LoadUint64(&m.afterAddCounter) < 1 {
		return false
	}
	return true
}

// MinimockAddInspect logs each unmet expectation
func (m *TickAdderMock) MinimockAddInspect() {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TickAdderMock.Add with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterAddCounter) < 1 {
		if m.AddMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to TickAdderMock.Add")
		} else {
			m.t.Errorf("Expected call to TickAdderMock.Add with params: %#v", *m.AddMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && mm_atomic.LoadUint64(&m.afterAddCounter) < 1 {
		m.t.Error("Expected call to TickAdderMock.Add")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TickAdderMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TickAdderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TickAdderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddDone()
}
