projects := \
	1_emptyshell \
	2_1_create_game \
	2_2_get_status \
	2_3_guess_endpoint \
	3_domain \
	4_1_repository \
	4_3_mutex \
	5_play \
	6_6_query_param

%:
	@for project in $(projects); do (cd $${project}; make $@); done
